### swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: cloud-auth在线接口平台
    description: cloud-auth微服务相关接口

### Swagger 鉴权
swagger:
  basic:
    enable: true
    username: tianqingzhao
    password: 123456

spring:
  main:
    ### 是否允许相同的bean存在，spring-boot中默认值为false，spring-framework中默认值为true
    ### 如果不设置为true，根据beanName找到相同的bean，直接抛出异常，设置为true会覆盖之前的bean
    allow-bean-definition-overriding: true

### Mybatis-Plus 配置 mapper.xml 文件映射路径
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml