mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

#security:
#  oauth2:
#    resource:
#      id: order-service

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: account-dubbo
  consumer:
    check: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  sentinel:
    enabled: true

# within rocketmq
rocketmq:
  name-server: 81.70.157.38:9876
  producer:
    group: cloud-group

# 指定日志级别
logging:
  level:
    com.alibaba.nacos: error

seata:
  enabled: true
  application-id: ${spring.application.name}-seata
  tx-service-group: order_service_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: 7a7e435c-73e4-4204-9191-72ee3d4a1767
      serverAddr: 81.70.157.38:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "tqz123456789."
  registry:
    type: nacos
    nacos:
      application: seata-server
      namespace: 7a7e435c-73e4-4204-9191-72ee3d4a1767
      server-addr: 81.70.157.38:8848
      userName: "nacos"
      password: "tqz123456789."