mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

service:
  name:
    account: http://account-service/
    product: http://product-service/

#security:
#  oauth2:
#    resource:
#      id: order-service

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: account-dubbo
  consumer:
    check: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  sentinel:
    enabled: true

# 指定日志级别
logging:
  level:
    com.alibaba.nacos: error

## swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: product-service在线接口平台
    description: product-service微服务相关接口

### Swagger 鉴权
swagger:
  basic:
    enable: true
    username: tianqingzhao
    password: 123456