server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.157.38:8848
        namespace: 7a7e435c-73e4-4204-9191-72ee3d4a1767
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service # 在所有路由定义中需要唯一，不能重复
          uri: lb://product-service #  lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
          predicates: ##Path=/product/** 使用"Path Route Predicate Factory"，规则为/product/** 的请求都还转发至微服务product-service中。
            - Path=/product/**
        - id: account-service # 在所有路由定义中需要唯一，不能重复
          uri: lb://account-service  #lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
          predicates: #Path=/product/** 使用"Path Route Predicate Factory"，规则为/product/** 的请求都还转发至微服务product-service中。
            - Path=/account/**
        - id: order-service # 在所有路由定义中需要唯一，不能重复
          uri: lb://order-service  # lb://** lb://为固定写法，表示开启负载均衡； ** 即服务在Nacos中注册的名字
          predicates: # Path=/product/** 使用"Path Route Predicate Factory"，规则为/product/** 的请求都还转发至微服务product-service中。
            - Path=/order/**