### Mybatis-Plus映射mapper.xml文件路径
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

#security:
#  oauth2:
#    resource:
#      id: account-service


logging:
  level:
    root: info
    org.springframework.security: debug

## swagger自定义配置属性
javadaily:
  swagger:
    enabled: true
    title: account-service在线接口平台
    description: account-service微服务相关接口


rocketmq:
  name-server: 81.70.157.38:9876
  producer:
    group: cloud-group


seata:
  enabled: true
  application-id: ${spring.application.name}-steata
  tx-service-group: account_service_seata
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: 7a7e435c-73e4-4204-9191-72ee3d4a1767
      server-addr: 81.70.157.38:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "tqz123456789."
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 81.70.157.38:8848
      namespace: 7a7e435c-73e4-4204-9191-72ee3d4a1767
      userName: "nacos"
      password: "tqz123456789."
#  service:
#    vgroup-mapping: seata-server-cluster

