mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

# oauth2.0
security:
  oauth2:
    resource:
      id: product-service


## swagger自定义配置属性
tqz:
  swagger:
    enabled: true
    title: product-service在线接口平台
    description: product-service微服务相关接口

### Swagger 鉴权
swagger:
  basic:
    enable: true
    username: tianqingzhao
    password: 123456

seata:
  service:
    vgroup-mapping: